
INSERT INTO USER (BIRTH_DATE, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PHONE, ROLE, USERNAME) 
VALUES ('25.01.2000', 'kl@gmail.com', 'Lana', 'Kovacevic', 'veb021', '0604706707', 'KORISNIK', 'lanak');

INSERT INTO USER (BIRTH_DATE, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PHONE, ROLE, USERNAME) 
VALUES ('10.09.1996', 'sp@gmail.com', 'Stefan', 'Panzalovic', 'lana22', '060123456', 'KORISNIK', 'panzal');

INSERT INTO CINEMA (ADRESS, E_MAIL, MANAGER, NAME, PHONE_NUMBER) 
VALUES ('Jugoslovenske Armije 6', 'bioskop@gmail.com', 'Olja', 'Bioskop', '0604706707');

INSERT INTO CINEMA_HALL (CAPACITY, HALL_MARK, CINEMA_ID) VALUES (100, 'sala1', 1);

INSERT INTO CINEMA_HALL (CAPACITY, HALL_MARK, CINEMA_ID) VALUES (150, 'sala2', 1);

INSERT INTO CINEMA_HALL (CAPACITY, HALL_MARK, CINEMA_ID) VALUES (70, 'sala3', 1);

INSERT INTO MOVIE (AVERAGE_RATING, DESCRIPTION, DURATION, GENRE, TITLE) 
VALUES (8.8, 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.','2.03', 'Sci-Fi', 'Inception');

INSERT INTO MOVIE (AVERAGE_RATING, DESCRIPTION, DURATION, GENRE, TITLE) 
VALUES (6.6, 'Nicky Spurgeon is an extremely accomplished con man who takes an amateur con artist, Jess, under his wing','2.02', 'Drama', 'Focus');

INSERT INTO MOVIES_WATCHED (USER_ID, MOVIE_ID) VALUES (1, 1);

INSERT INTO MOVIES_WATCHED (USER_ID, MOVIE_ID) VALUES (1, 2);

INSERT INTO MOVIES_WATCHED (USER_ID, MOVIE_ID) VALUES (2, 1);

INSERT INTO MOVIE_RATING (MOVIE_ID, USER_ID, RATING) VALUES (1, 2, 6.6);

INSERT INTO MOVIE_RATING (MOVIE_ID, USER_ID, RATING) VALUES (2, 1, 8.8);

INSERT INTO TICKETS_RESERVED (USER_ID, MOVIE_ID) VALUES (2, 2);

INSERT INTO SCREENING (DATE_AND_TIME, PRICE, CINEMA_ID, MOVIE_ID) VALUES ('2020-05-20 18:00:00', 350, 1, 1);

INSERT INTO PROJECTION (TICKETS_RESERVED, SCREENING_ID) VALUES (0, 1);

INSERT INTO SCREENING (DATE_AND_TIME, PRICE, CINEMA_ID, MOVIE_ID) VALUES ('2020-05-20 20:00:00', 300, 1, 2);

INSERT INTO PROJECTION (TICKETS_RESERVED, SCREENING_ID) VALUES (1, 2);

INSERT INTO SCREENING (DATE_AND_TIME, PRICE, CINEMA_ID, MOVIE_ID) VALUES ('2020-05-21 20:00:00', 350, 1, 1);

INSERT INTO PROJECTION (TICKETS_RESERVED, SCREENING_ID) VALUES (0, 3);

INSERT INTO SCREENING (DATE_AND_TIME, PRICE, CINEMA_ID, MOVIE_ID) VALUES ('2020-05-21 20:00:00', 300, 1, 2);

INSERT INTO PROJECTION (TICKETS_RESERVED, SCREENING_ID) VALUES (0, 4);

INSERT INTO PROJECTION_SCHEDULE (HALL_ID, PROJECTION_ID) VALUES (1, 1);

INSERT INTO PROJECTION_SCHEDULE (HALL_ID, PROJECTION_ID) VALUES (3, 2);

INSERT INTO PROJECTION_SCHEDULE (HALL_ID, PROJECTION_ID) VALUES (2, 2);

INSERT INTO PROJECTION_SCHEDULE (HALL_ID, PROJECTION_ID) VALUES (3, 3);

INSERT INTO PROJECTION_SCHEDULE (HALL_ID, PROJECTION_ID) VALUES (1, 4);



