
INSERT INTO USER (BIRTH_DATE, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PHONE, ROLE, USERNAME) 
VALUES ('25.01.2000', 'kl@gmail.com', 'Lana', 'Kovacevic', 'veb021', '0604706707', 'KORISNIK', 'lanak');

INSERT INTO USER (BIRTH_DATE, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PHONE, ROLE, USERNAME) 
VALUES ('18.09.1999.', 'petarp@gmail.com', 'Petar', 'Petrovic', 'pass123', '065684150', 'ADMINISTRATOR', 'pero00');

INSERT INTO USER (BIRTH_DATE, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PHONE, ROLE, USERNAME) 
VALUES ('14.02.1990.', 'jovo@gmail.com', 'Jovan', 'Jovanovic', 'lozinka123', '0625826292', 'ADMINISTRATOR', 'Jole');

INSERT INTO USER (BIRTH_DATE, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PHONE, ROLE, USERNAME) 
VALUES ('01.05.1999.', 'veb@gmail.com', 'Marko', 'Markovic', 'proj01', '0635896393', 'ADMINISTRATOR', 'admin');

INSERT INTO USER (BIRTH_DATE, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PHONE, ROLE, USERNAME) 
VALUES ('18.05.1998.', 'nole@gmail.com', 'Novak', 'Djokovic', 'volimtenis123', '0645801474', 'MENADZER', 'djovak');

INSERT INTO USER (BIRTH_DATE, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PHONE, ROLE, USERNAME) 
VALUES ('18.05.1998.', 'petar@gmail.com', 'Petar', 'Krsmanovic', 'pametan', '0645801474', 'MENADZER', 'petarNjegos');

INSERT INTO USER (BIRTH_DATE, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PHONE, ROLE, USERNAME) 
VALUES ('18.05.1998.', 'milan@gmail.com', 'Milan', 'Cavarabdzic', 'glupan', '0645801474', 'MENADZER', 'Kostarika');

INSERT INTO USER (BIRTH_DATE, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PHONE, ROLE, USERNAME) 
VALUES ('20.01.1986.', 'adresa@gmail.com', 'Imenko', 'Prezimenic', 'loz123', '0625826325', 'KORISNIK', 'imenko');

INSERT INTO USER (BIRTH_DATE, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PHONE, ROLE, USERNAME) 
VALUES ('13.02.1995.', 'mejl@gmail.com', 'Ivan', 'Ivanovic', 'vece', '0604706707', 'KORISNIK', 'IvanOvic');

INSERT INTO MOVIE (AVERAGE_RATING, DESCRIPTION, DURATION, GENRE, TITLE, IMAGE_FILE_NAME) 
VALUES (8.8, 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.', '2.03', 'Sci-Fi', 'Inception', '1.jpg');

INSERT INTO MOVIE (AVERAGE_RATING, DESCRIPTION, DURATION, GENRE, TITLE, IMAGE_FILE_NAME) 
VALUES (6.6, 'Nicky Spurgeon is an extremely accomplished con man who takes an amateur con artist, Jess, under his wing','2.02', 'Drama', 'Focus', '2.jpg');

INSERT INTO MOVIE (AVERAGE_RATING, DESCRIPTION, DURATION, GENRE, TITLE, IMAGE_FILE_NAME) 
VALUES (4.3, 'Opis filma','1.54', 'Comedy', '21 Jump Street', '3.jpg');

INSERT INTO MOVIE (AVERAGE_RATING, DESCRIPTION, DURATION, GENRE, TITLE, IMAGE_FILE_NAME) 
VALUES (7.2, 'Movie description', '1.53', 'Romance', 'Romance Movie', '4.jpg');

INSERT INTO MOVIE (AVERAGE_RATING, DESCRIPTION, DURATION, GENRE, TITLE, IMAGE_FILE_NAME) 
VALUES (9.3, 'Description of a movie','2.20', 'Drama', 'Drama movie', '5.jpg');

INSERT INTO MOVIE (AVERAGE_RATING, DESCRIPTION, DURATION, GENRE, TITLE, IMAGE_FILE_NAME) 
VALUES (5.0, 'Opis jos jednog filma','2.07', 'Comedy', 'Comedy Movie', '6.jpg');

INSERT INTO MOVIE (AVERAGE_RATING, DESCRIPTION, DURATION, GENRE, TITLE, IMAGE_FILE_NAME) 
VALUES (9.7, 'Jako dobar film','2.00', 'Sci-Fi', 'Best Movie Ever', '7.jpg');

INSERT INTO MOVIE (AVERAGE_RATING, DESCRIPTION, DURATION, GENRE, TITLE, IMAGE_FILE_NAME) 
VALUES (2.1, 'Jako los film', '1.52', 'Comedy', 'Worst Movie Ever', '8.jpg');

INSERT INTO MOVIE (AVERAGE_RATING, DESCRIPTION, DURATION, GENRE, TITLE, IMAGE_FILE_NAME) 
VALUES (7.7, 'Najgledaniji film', '1.50', 'Action', 'Most Popular Movie Ever', '9.jpg');

INSERT INTO CINEMA (ADRESS, E_MAIL, MANAGER, NAME, PHONE_NUMBER) 
VALUES ('Jugoslovenske Armije 6', 'bioskop@gmail.com', 'Olja', 'Bioskop', '0604706707');

INSERT INTO CINEMA (ADRESS, E_MAIL, MANAGER, NAME, PHONE_NUMBER) 
VALUES ('Blagoja Parovica 92', 'cinema@gmail.com', 'Pero', 'Cinema', '0604485407');

INSERT INTO CINEMA (ADRESS, E_MAIL, MANAGER, NAME, PHONE_NUMBER) 
VALUES ('Bulevar Oslobodjenja', 'theatre@gmail.com', 'Janko', 'Movie Theatre', '0603816797');

INSERT INTO CINEMA_HALL (CAPACITY, HALL_MARK, CINEMA_ID) VALUES (100, 'sala 1', 1);

INSERT INTO CINEMA_HALL (CAPACITY, HALL_MARK, CINEMA_ID) VALUES (150, 'sala 2', 1);

INSERT INTO CINEMA_HALL (CAPACITY, HALL_MARK, CINEMA_ID) VALUES (70, 'sala 3', 1);

INSERT INTO CINEMA_HALL (CAPACITY, HALL_MARK, CINEMA_ID) VALUES (100, 'hall 1', 2);

INSERT INTO CINEMA_HALL (CAPACITY, HALL_MARK, CINEMA_ID) VALUES (150, 'hall 2', 2);

INSERT INTO CINEMA_HALL (CAPACITY, HALL_MARK, CINEMA_ID) VALUES (70, 'hall 3', 2);

INSERT INTO CINEMA_HALL (CAPACITY, HALL_MARK, CINEMA_ID) VALUES (100, 'hall 1-1', 3);

INSERT INTO CINEMA_HALL (CAPACITY, HALL_MARK, CINEMA_ID) VALUES (150, 'hall 1-2', 3);

INSERT INTO CINEMA_HALL (CAPACITY, HALL_MARK, CINEMA_ID) VALUES (70, 'hall 2-1', 3);


INSERT INTO PROJECTION (DATE_AND_TIME, PRICE, TICKETS_RESERVED, MOVIE_ID) VALUES ('2020-05-25 18:30:00', 300, 3, 2);

INSERT INTO PROJECTION (DATE_AND_TIME, PRICE, TICKETS_RESERVED, MOVIE_ID) VALUES ('2020-05-26 18:00:00', 300, 1, 1);

INSERT INTO PROJECTION (DATE_AND_TIME, PRICE, TICKETS_RESERVED, MOVIE_ID) VALUES ('2020-05-25 18:30:00', 350, 5, 2);

INSERT INTO PROJECTION (DATE_AND_TIME, PRICE, TICKETS_RESERVED, MOVIE_ID) VALUES ('2020-06-24 15:30:00', 250, 3, 3);

INSERT INTO PROJECTION (DATE_AND_TIME, PRICE, TICKETS_RESERVED, MOVIE_ID) VALUES ('2020-05-27 19:15:00', 300, 7, 5);

INSERT INTO PROJECTION (DATE_AND_TIME, PRICE, TICKETS_RESERVED, MOVIE_ID) VALUES ('2020-05-27 20:30:00', 400, 3, 9);

INSERT INTO PROJECTION (DATE_AND_TIME, PRICE, TICKETS_RESERVED, MOVIE_ID) VALUES ('2020-05-26 21:30:00', 250, 3, 7);

INSERT INTO PROJECTION (DATE_AND_TIME, PRICE, TICKETS_RESERVED, MOVIE_ID) VALUES ('2020-05-26 21:30:00', 300, 3, 8);

INSERT INTO PROJECTION_SCHEDULE(HALL_ID, PROJECTION_ID) VALUES (1, 1);

INSERT INTO PROJECTION_SCHEDULE(HALL_ID, PROJECTION_ID) VALUES (2, 3);

INSERT INTO PROJECTION_SCHEDULE(HALL_ID, PROJECTION_ID) VALUES (3, 2);

INSERT INTO PROJECTION_SCHEDULE(HALL_ID, PROJECTION_ID) VALUES (4, 5);

INSERT INTO PROJECTION_SCHEDULE(HALL_ID, PROJECTION_ID) VALUES (5, 8);

INSERT INTO PROJECTION_SCHEDULE(HALL_ID, PROJECTION_ID) VALUES (8, 7);

INSERT INTO PROJECTION_SCHEDULE(HALL_ID, PROJECTION_ID) VALUES (9, 6);

INSERT INTO PROJECTION_SCHEDULE(HALL_ID, PROJECTION_ID) VALUES (3, 4);

INSERT INTO MANAGER_CINEMA(MANAGER_ID, CINEMA_ID)
VALUES (5, 1);

INSERT INTO MANAGER_CINEMA(MANAGER_ID, CINEMA_ID)
VALUES (5, 2);
